import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://myezra-staging.ezra.com/sign-in');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('testing4@gm.co');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Testing@1357');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Book a scan' }).click();
  await page.getByText('MRI Scan Available at $').click();
  await page.getByTestId('select-plan-submit-btn').click();
  await page.getByText('Recommended AMRICNew York,').click();
  await page.getByTestId('3-19-cal-day-content').click();
  await page.getByText(':00 AM').first().click();
  await page.locator('[data-test="submit"]').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Card number' }).click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Card number' }).fill('4242 4242 4242 4242');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Expiration date MM / YY' }).fill('12 / 27');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Security code' }).fill('234');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Postal code' }).fill('554 43');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Postal code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Postal code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Postal code' }).press('ArrowDown');
  await page.getByText('$').nth(1).click();
  await page.locator('[data-test="submit"]').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Postal code' }).click();
  await page.locator('.buttons').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByLabel('Country').selectOption('US');
  await page.locator('[data-test="submit"]').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).click();
  await page.locator('.buttons').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).click();
  await page.locator('.buttons').click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Expiration (MM/YY) MM / YY' }).click();
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Expiration (MM/YY) MM / YY' }).press('Tab');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'Security code' }).press('Tab');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByLabel('Country').press('Tab');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).press('ArrowDown');
  await page.locator('iframe[name="__privateStripeFrame82314"]').contentFrame().getByRole('textbox', { name: 'ZIP code' }).fill('55443');
  await page.locator('[data-test="submit"]').click();
  await page.goto('https://myezra-staging.ezra.com/sign-up/scan-confirm');
  await page.getByRole('link', { name: 'Home' }).click();
});